### ISSUE TITLE
Language settings are initialized when moving from one page to another

### ISSUE THREAD

**Issue by develoQ** [Bithomp/frontend-react#43]
When going from an `a` tag to another page, it is forced to reset to English.

You should probably use `Link` (Next/link) instead of `a` tag.

For example, if you select other than English in https://bithomp.com/nfts, when you click on the `NFT OFFERS` tab, the page you are taken to will be displayed in English.
![スクリーンショット 2023-09-15 20 54 30](https://github.com/Bithomp/frontend-react/assets/69445828/450c3fd4-2089-4230-983b-c66ad22bbfef)

https://github.com/Bithomp/frontend-react/blob/main/components/Layout/SearchBlock.js#L373-L378

**Comment by develoQ** [comment]
It seems that you are not using `Link` in the next two files where it should be used.

https://github.com/Bithomp/frontend-react/blob/main/pages/nft-volumes/%5Bissuer%5D.js
https://github.com/Bithomp/frontend-react/blob/main/pages/nft-volumes/index.js

**Comment by develoQ** [comment]
It seems that other places that can be searched with `<a href={"/nft` should also be fixed.

**Comment by ihomp** [comment]
Oops, I was too fast to close the issue :( Thanks for reporting @develoQ 

That should be fixed with the last three commits, deployed to the mainnet.

https://github.com/Bithomp/frontend-react/commit/a3ea36b00c78217104c42bc369b4253553088e90
https://github.com/Bithomp/frontend-react/commit/b0f8c232f2c397954bf2e619ea790866fd736b44
https://github.com/Bithomp/frontend-react/commit/1abda332107d6682aaad7ab012c9f27cf4651785

**Comment by develoQ** [comment]
The language has also changed when searching on these pages.

https://bithomp.com/nfts
https://bithomp.com/nft-offers

This is due to the use of `window.location`. You should use `useRouter`.
- `components/Layout/SearchBlock.js`

**Comment by ihomp** [comment]
I couldn't replicate the issue, but I've replaced the `window.location` with `redirect`

https://github.com/Bithomp/frontend-react/commit/9d572d8ead1f82f6058e15cd884cd4af5cbdea89

Hopefully, that fixes the issue.

**Comment by ihomp** [comment]
`redirect` didn't work well, replaced with `router.push`
https://github.com/Bithomp/frontend-react/commit/6c257a972b912bbb7d6a7bd76dfcb3876ed83c54

**Comment by ihomp** [comment]
is it ok to close it now @develoQ ? ;)

**Comment by develoQ** [comment]
Okay! thanks!
