### ISSUE TITLE
Translation with variables

### ISSUE THREAD

**Issue by develoQ** [Bithomp/frontend-react#45]
Some content cannot be accurately translated because the order of its strings has been fixed.

1. `table.text.see-on`
    `See on xrp.cafe` should be translated as `xrp.cafeで見る` in Japanese, but the marketplace name is fixed behind.

2. `by` (domains.json)

3. `nft.cancel-sell-offer-for`
4. `nft.cancel-buy-offer-for`
5. `nft.buy-for`
6. `username.error.address-hosted.on`

I will comment on others as soon as I find them.

**Comment by ihomp** [comment]
1. https://github.com/Bithomp/frontend-react/commit/8f233498f24b45da407096246a15b446e3d1df3e

**Comment by ihomp** [comment]
2. https://github.com/Bithomp/frontend-react/commit/da57b428a94c164d10eae1933b84d07ee7a95f4c

**Comment by ihomp** [comment]
3, and 4. 
https://github.com/Bithomp/frontend-react/commit/0a002796df61338d3ec8ca0eef7ec49033cd171c

**Comment by ihomp** [comment]
5. https://github.com/Bithomp/frontend-react/commit/accc9f235f69e20be8eed42950cd6ee03597901a

**Comment by ihomp** [comment]
6. https://github.com/Bithomp/frontend-react/commit/f90c52ee5ae2c8fe4870ceff68e962ce68b52999

**Comment by ihomp** [comment]
So, the missing translations are now:

`domains.json`
line 10: "toml-editor"

`common.json`
lines 577, 578
lines 581-584

@develoQ can you help with that?

**Comment by develoQ** [comment]
Yes, sure!

**Comment by ihomp** [comment]
Thank you, that was fast! 
let's open a new issue or reopen this one in case new cases like that will be found. 
I'll close this one for now.
