### ISSUE TITLE
Broken string `tabs.all-sales-sales`

### ISSUE THREAD

**Issue by develoQ** [Bithomp/frontend-react#46]
https://bithomp.com/nft-volumes?sale=all-sales

![スクリーンショット 2023-09-16 12 06 00](https://github.com/Bithomp/frontend-react/assets/69445828/9cd22939-b819-4db6-a1c7-9303ecfca61d)

May be should `tabs.all-sales`.

**Comment by ihomp** [comment]
It seems I broke it a few days ago, thanks for reporting it.
It should be fixed now with
https://github.com/Bithomp/frontend-react/commit/907cfe18c72407517219676e694fa4d6cd5d6e05
