### ISSUE TITLE
Header name of NFTokenAcceptOffer form

### ISSUE THREAD

**Issue by develoQ** [Bithomp/frontend-react#47]
`signin.confirm.nft-accept-offer-header`: `NFT purchase`

Since NFTokenAcceptOffer is used to sell as well as buy NFTs, this header name may not be suitable.

**Comment by ihomp** [comment]
Oh, you're right.
I've just realized we do not have the option to SELL by accepting the NFT buy offer yet. 
I'll add that option and fix the namings. 
Thanks.

**Comment by ihomp** [comment]
It is now split into two pieces.
Can you translate them? @develoQ common.js, lines 104-105
https://github.com/Bithomp/frontend-react/blob/main/public/locales/ja/common.json#L104

Thanks

**Comment by develoQ** [comment]
- #60

**Comment by ihomp** [comment]
That was quick, thanks a lot!
