### ISSUE TITLE
Not using `table.time`?

### ISSUE THREAD

**Issue by develoQ** [Bithomp/frontend-react#48]
I thought that `table.time` was not being used.

It seems to me that it was a field that should have been deleted at the same time when the `NftSalesLatest.js` file was deleted.

**Comment by ihomp** [comment]
You're right, it is not in use, I've just decided to leave it, as it was already translated into all the languages we have, and it's a quite general single word. I thought it very likely I'd use it again. 

I've removed it for now, so we don't have unused ones. 
https://github.com/Bithomp/frontend-react/commit/5e3d264b0106612a8b91dd17e44db3a1837c820f
